### ISSUE TITLE
Is it possible to use other fonts(embeded ttf)?

### ISSUE THREAD

**Issue by suzumiyasmith** [alpheccar/HPDF#12]
The font setting for a text can only be one of the default 14 basic fonts. Is it possible to embed some customed font in the pdf?  [(for more detail)](https://www.wiwi.hu-berlin.de/de/professuren/quantitativ/statistik/doc/formulare/embedfonts.pdf)

**Comment by alpheccar** [comment]
I am working on it but since I really don't have a lot of free time it is progressing very slowly. I have currently something working with Type1 font (should be possible to extend to TTF after). All strings in my version are now encoded in UTF8. But I still need some work to support the different encoding in addition to UTF8. So, all I can say : be very patient. It will come someday.
