### ISSUE TITLE
Writing PNGs?

### ISSUE THREAD

**Issue by nomeata** [alpheccar/HPDF#6]
Hi,

it seems that http://hackage.haskell.org/package/HPDF-1.4.8/docs/Graphics-PDF-Image.html supports only JPGs. What about other image formats, in particular PNG? Or do I have to manually convert it into the format accepted by `createPDFRawImage`? Will this not lose compression then?

Thanks,
Joachim

**Comment by alpheccar** [comment]
Hi,

Indeed, PNG are not directly supported in PDF so they are not as easy to embed in the PDF. 

So you'll have to use the raw uncompressed pictures. I may have added some compression for raw pictures since it is supported for PDF. But it is not done in current version of HPDF. 

You can enable compression at the I document  level but of course it will be less efficient than a compression designed for pictures.

**Comment by nomeata** [comment]
Actually, in my case the graphics are highly repetitive, so document level compression is a good start. And I guess I can do the conversion with JuicyPixels. Thanks for your input!
